version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: my-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - redis-net
    volumes:
      - "./redis-data:/data"

networks:
  redis-net:
    driver: bridge
